title: "SIMBA+"
description: "API reference and documentation for SIMBA+"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM

# Ensure the generated API HTML is included in the site build
include:
  - api
